### PR TITLE
ATOM 5430 handle po box addresses

### PR DESCRIPTION
**Pull request by pedromartinez**

### CODE REVIEW

**Comment by mgates** [comment]
Can you do the rubocop fixes in a separate PR? (or not at all?)

**Comment by pedromartinez** [comment]
@mgates Is that necessary? I put it in a separate commit so it's easy to review the actual changes.

**Comment by pedromartinez** [comment]
@mgates If you insist, I can cherry-pick it to master.

**Comment by mgates** [comment]
I would prefer that, but only if it's not a huge PITA.

**Comment by pedromartinez** [comment]
Yay, conflicts.

**Comment by mgates** [comment]
LGTM, though, assuming that that is the right XML to send.

**Pull request closed without merging**
