### PR TITLE
this adds query port in messages api

### PR DESCRIPTION
**Pull request by dougperez**

### CODE REVIEW

**Comment by mgates** [comment]
what does this let you do?

**Comment by pedromartinez** [comment]
👍

**Comment by dougperez** [comment]
This lets us query port-in request from sprint's ```query_pending_reseller_port_ins``` api. Basically when a number port is submitted we are going to hit this api instead of query port all message and sift through them for port-ins.

**Comment by captainbeardo** [comment]
👍

**Pull request merged**
