### PR TITLE
fix query_device_info iccid node placement

### PR DESCRIPTION
**Pull request by davidtrogers**

### CODE REVIEW

**Comment by pedromartinez** [comment]
:+1:

**Comment by pedromartinez** [comment]
Just checking, did all the tests pass?  We have no CI on this right now.

**Comment by davidtrogers** [comment]
@pedromartinez yes: 
```
Finished in 0.40168 seconds (files took 0.22773 seconds to load)
269 examples, 0 failures
```

**Comment by pedromartinez** [comment]
:+1:

**Pull request merged**
