### PR TITLE
need to protect again there being no device_serial_number

### PR DESCRIPTION
**Pull request by dougperez**

### CODE REVIEW

**Comment by pedromartinez** [comment]
:-1:

**Comment by mgates** [comment]
Why, @pedromartinez

**Comment by pedromartinez** [comment]
Doug and I were discussing this on Slack.  I just wanted to put a comment showing that neither of us thought this was the proper solution.

That value is a required field and should have been caught upstream.

**Comment by arvanasse** [comment]
Merged #80 per @pedromartinez

**Pull request merged**
